services:

  broker:
    build:
      context: .
      dockerfile: Dockerfile_broker
    container_name: broker
    ports:
      - 5555:5555

  servidor:
    build:
      context: .
      dockerfile: Dockerfile_servidor
    depends_on:
      - broker
    deploy:
      replicas: 3

  cliente:
    build:
      context: .
      dockerfile: Dockerfile_cliente
    depends_on:
      - servidor
    deploy:
      replicas: 2